### ISSUE TITLE
Add NA protein to BLAST libraries, make functional for the HA Identity Tool

### ISSUE THREAD

**Issue by mazeller** [mazeller/FLUture#11]
1. Add pulling and formatting of NA sequences to the weekly cronjob
2. Check code for HA/NA specific logic as needed
3. Address how to handle the two pie charts in the case of NA
4. Ask Dr. Gauger for new potential names of the tool that reflect the ability to handle both the NA and HA
5. Classify NA down to the subclade level (2002.A/2002.B), see related NA classification issue.

**Comment by tkanderson** [comment]
Hi Michael, please do not classify the NA-N2 to finer resolution. This is a work in progress paper, and it is better to keep that option out of the public domain until it is published.

**Comment by mazeller** [comment]
All done except for consideration of a new name (#4). This issue will be re-opened f a new name is in order.
