### ISSUE TITLE
Add sorting index ha_clade and na_clade tables

### ISSUE THREAD

**Issue by mazeller** [mazeller/FLUture#13]
A new column should be added to these table to indicate sorting order. In the future, a new query will be added that will grab the sorting order from the database.

**Comment by mazeller** [comment]
This will also replace the hard coded clades in js/dataloader.js on line 175.

**Comment by anugrah-saxena** [comment]
Column addition completed.
TODO: query to grab sort order and replace dataloader static code.

**Comment by anugrah-saxena** [comment]
dataloader now uses the H1 and H3 clade array (sorted in greek order) values gathered from the ajax request.
Also, made the code more modular to allow future addition of diagnostic code data, etc. in dataloader and in getdata api
