### ISSUE TITLE
https and ssl certificate

### ISSUE THREAD

**Issue by tkanderson** [mazeller/FLUture#17]
The absence of https and SSL is a problem for some biologic companies. Even though this is not a major issue for FLUture (no passwords, etc.), this should be something high on the priority list. The "not secure" flag that comes up when visiting the site is not comforting.

We use Certbot (https://certbot.eff.org/) for our database, I am sure ISU has something similar. I'd recommend getting things moving on this with the network people.

**Comment by mazeller** [comment]
The certificates have been ordered and received. Websites are currently being set up. Will likely use the rewrite engine to default to the HTTPS version of the site.

**Comment by mazeller** [comment]
Our server admins have aquired a 2 year SSL cert. Server's have been set up accordingly. HTTPS is now the default.
