### ISSUE TITLE
Update BLAST based HA Identity Tool

### ISSUE THREAD

**Issue by mazeller** [mazeller/FLUture#19]
The tool needs to function with the new database structure.
Additionally citations need to be added for upcoming paper. 
Finally, the tool should consider noting the origin  [C/P/T] of the top blast hit in question.

**Comment by SiyingLyu** [comment]
Updates were done through db.php file.

**Comment by mazeller** [comment]
Need to add citation if accepted in MRA.

**Comment by mazeller** [comment]
Added citation.
