### ISSUE TITLE
Sidebar update - correct link on General IAV information

### ISSUE THREAD

**Issue by tkanderson** [mazeller/FLUture#21]
The https://influenza.cvm.iastate.edu/ sidebar has a link out to "General Influenza information" hosted at the NPB. 

It would be better to have this link as a new page rather than load over FLUture.

**Comment by mazeller** [comment]
This issue can be resolved with a _target="blank", but it needs to work in the following context; https://www.sample.iastate.edu/download/php/

**Comment by SiyingLyu** [comment]
Bug fixed in both dev and live server. Changes committed.

**Comment by tkanderson** [comment]
The side menu bar now links out to a new page for all tools on FLUture. Best to just have this for the "General Influenza Information" which is to an external NPB page vs. staying on iastate. Thanks.

**Comment by SiyingLyu** [comment]
Bug fixed in both dev and live server.
