### ISSUE TITLE
Add pesudo admin for certain risky query operations

### ISSUE THREAD

**Issue by anugrah-saxena** [mazeller/FLUture#26]
Add pseudo admin user to database and also for processing certain requests update database connection.
New suggestions welcome

**Comment by anugrah-saxena** [comment]
Updates done in DEV.
Added new user with privileges to Select, Update and Delete queries.
Also, updated the config and db connect

**Comment by SiyingLyu** [comment]
Added 'Lock tables' and 'Show view' privilege to flumate
