### ISSUE TITLE
Remove zero count items from the hover in time series and correlation

### ISSUE THREAD

**Issue by mazeller** [mazeller/FLUture#31]
Currently, if as % is checked, items with 0 percent are removed. This functionality should continue if raw numbers are used in correlation and time series.

**Comment by anugrah-saxena** [comment]
Fixed in DEV, cross-checked and pushed.

**Comment by mazeller** [comment]
Please add those zeros back in for time-series, or else the lines do no connect.

**Comment by anugrah-saxena** [comment]
ok

**Comment by mazeller** [comment]
Set y-min to zero for time-series.

**Comment by anugrah-saxena** [comment]
y-min set to 0 according to issue #33
