### ISSUE TITLE
Heatmap use order from database

### ISSUE THREAD

**Issue by anugrah-saxena** [mazeller/FLUture#44]
Change coe to use H1 & H3 order from database instead of static code

**Comment by mazeller** [comment]
Both H1 and H3 clades.

**Comment by anugrah-saxena** [comment]
@mazeller H1 thanks for pointing it out. I missed about H4. So, to ignore that as you said H3 will be needed :)

**Comment by anugrah-saxena** [comment]
Done in live and dev.
