### ISSUE TITLE
Identify a good tree drawing solution

### ISSUE THREAD

**Issue by mazeller** [mazeller/FLUture#8]
FLUture would benefit from having phylogenetic trees present on the website. A javascript solution that allows interactable trees that have hover and click events on the leaves, and are easily recolored and sorted would be optimal. Resources need to be discovered to determine if this can be done from currently available libraries, or needs to be developed in house.

**Comment by mazeller** [comment]
Tree functionality would ideally be similar to Trevor Bedford & Richard Neher's nextstrain https://nextstrain.org/flu/seasonal/h3n2/ha/3y

**Comment by tkanderson** [comment]
A potential option is icytree: https://icytree.org/

**Comment by tkanderson** [comment]
Another option here: https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkz356/5494736 

https://phylogeny.io

**Comment by SiyingLyu** [comment]
The phylotree.js is used for the virtualization of the phylogenetic tree (http://phylotree.hyphy.org/documentation/)
